[package]
name = "caddy_reverse_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
headless-chrome = "0.17.0"
tokio = { version = "1", features = ["full"] }
once_cell = "1.18.0"
log = "0.4"
env_logger = "0.10"
toml = "0.5.9"
serde = { version = "1.0", features = ["derive"] }
